use teloxide::prelude::*;
use teloxide::types::{ChatId, InputFile};

use crate::error::{Error, Result};
use crate::vpn::model::{human_bytes, AddResult, Client};

pub fn format_client_card(c: &Client) -> String {
    let status = if !c.status.is_empty() {
        c.status.clone()
    } else if c.active() {
        "активен".to_string()
    } else {
        "отключён".to_string()
    };
    format!(
        "client: {name}\nстатус: {status}\nтрафик: ↓ {rx}  ↑ {tx}",
        name = c.name,
        rx = human_bytes(c.rx),
        tx = human_bytes(c.tx),
    )
}

pub fn format_stats(clients: &[Client]) -> String {
    let total = clients.len();
    let active = clients.iter().filter(|c| c.active()).count();
    let rx: u64 = clients.iter().map(|c| c.rx).sum();
    let tx: u64 = clients.iter().map(|c| c.tx).sum();
    format!(
        "📊 Статистика\nВсего клиентов: {total}\nАктивных: {active}\nТрафик суммарно: ↓ {rx}  ↑ {tx}",
        rx = human_bytes(rx),
        tx = human_bytes(tx),
    )
}

pub async fn send_client_files(bot: &Bot, chat: ChatId, res: &AddResult) -> Result<()> {
    bot.send_document(chat, InputFile::file(&res.conf_path))
        .await
        .map_err(|e| Error::Telegram(e.to_string()))?;
    // QR and URI are generated by the script conditionally (e.g. only if `qrencode`
    // is installed) — only send them when they actually exist.
    if std::path::Path::new(&res.qr_path).exists() {
        bot.send_photo(chat, InputFile::file(&res.qr_path))
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    if !res.uri.is_empty() {
        bot.send_message(chat, format!("🔗 Ссылка для импорта:\n`{}`", res.uri))
            .parse_mode(teloxide::types::ParseMode::MarkdownV2)
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Client {
        Client {
            name: "alice".into(),
            ip: "10.0.0.2".into(),
            client_ipv6: String::new(),
            status: "Активен".into(),
            status_code: "active".into(),
            rx: 1288490188,
            tx: 356515840,
            last_handshake: Some(1752000000),
        }
    }

    #[test]
    fn card_contains_name_and_traffic() {
        let text = format_client_card(&sample());
        assert!(text.contains("alice"));
        assert!(text.contains("Активен"));
        assert!(text.contains("1.2 GB"));
    }

    #[test]
    fn stats_counts_clients() {
        let clients = vec![
            sample(),
            Client {
                name: "bob".into(),
                ip: "10.0.0.3".into(),
                client_ipv6: String::new(),
                status: "Неактивен".into(),
                status_code: "inactive".into(),
                rx: 0,
                tx: 0,
                last_handshake: None,
            },
        ];
        let text = format_stats(&clients);
        assert!(text.contains("2")); // всего клиентов
        assert!(text.contains("1")); // активных
    }
}
