use teloxide::prelude::*;
use teloxide::types::{ChatId, InputFile, InputMedia, InputMediaDocument, ParseMode};

use crate::error::{Error, Result};
use crate::i18n::{self, Lang};
use crate::vpn::model::{format_expiry, format_handshake, human_bytes, AddResult, Client};

pub fn format_client_card(lang: Lang, c: &Client, now: i64, expiry: Option<i64>) -> String {
    let status = i18n::status_label(lang, &c.status_code, &c.status);
    i18n::client_card(
        lang,
        &c.name,
        &status,
        &c.ip,
        &human_bytes(c.rx),
        &human_bytes(c.tx),
        &format_handshake(lang, now, c.last_handshake.unwrap_or(0)),
        &format_expiry(lang, now, expiry),
    )
}

pub fn format_stats(lang: Lang, clients: &[Client]) -> String {
    let total = clients.len();
    let active = clients.iter().filter(|c| c.active()).count();
    let rx: u64 = clients.iter().map(|c| c.rx).sum();
    let tx: u64 = clients.iter().map(|c| c.tx).sum();
    i18n::stats_summary(lang, total, active, &human_bytes(rx), &human_bytes(tx))
}

pub async fn send_client_files(bot: &Bot, chat: ChatId, lang: Lang, res: &AddResult) -> Result<()> {
    bot.send_document(chat, InputFile::file(&res.conf_path))
        .await
        .map_err(|e| Error::Telegram(e.to_string()))?;
    // QR and URI are generated by the script conditionally (e.g. only if `qrencode`
    // is installed) — only send them when they actually exist.
    if std::path::Path::new(&res.qr_path).exists() {
        bot.send_photo(chat, InputFile::file(&res.qr_path))
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    if !res.uri.is_empty() {
        bot.send_message(chat, i18n::import_link(lang, &res.uri))
            .parse_mode(ParseMode::Html)
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    Ok(())
}

/// Выдаёт `.conf`-файлы одним альбомом через `sendMediaGroup` (2–10 документов).
/// Используется при массовой генерации. Все элементы — одного типа (документы),
/// иначе Telegram отклонит альбом. `conf_paths` пуст → no-op (не ошибка).
pub async fn send_album(bot: &Bot, chat: ChatId, conf_paths: &[String]) -> Result<()> {
    match conf_paths {
        [] => Ok(()),
        [single] => {
            // sendMediaGroup требует 2–10 элементов; один конфиг шлём документом.
            bot.send_document(chat, InputFile::file(single))
                .await
                .map_err(|e| Error::Telegram(e.to_string()))?;
            Ok(())
        }
        paths => {
            let media: Vec<InputMedia> = paths
                .iter()
                .map(|p| InputMedia::Document(InputMediaDocument::new(InputFile::file(p))))
                .collect();
            bot.send_media_group(chat, media)
                .await
                .map_err(|e| Error::Telegram(e.to_string()))?;
            Ok(())
        }
    }
}

/// Авто-выдача после создания с учётом фильтра настроек. `conf/qr/link` —
/// тумблеры из `SettingsStore`; каждый артефакт шлётся только если включён и
/// существует (QR/ссылка условны — qrencode может отсутствовать).
pub async fn send_client_files_filtered(
    bot: &Bot,
    chat: ChatId,
    lang: Lang,
    res: &AddResult,
    conf: bool,
    qr: bool,
    link: bool,
) -> Result<()> {
    if conf {
        bot.send_document(chat, InputFile::file(&res.conf_path))
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    if qr && std::path::Path::new(&res.qr_path).exists() {
        bot.send_photo(chat, InputFile::file(&res.qr_path))
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    if link && !res.uri.is_empty() {
        bot.send_message(chat, i18n::import_link(lang, &res.uri))
            .parse_mode(ParseMode::Html)
            .await
            .map_err(|e| Error::Telegram(e.to_string()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Client {
        Client {
            name: "alice".into(),
            ip: "10.0.0.2".into(),
            client_ipv6: String::new(),
            status: "Активен".into(),
            status_code: "active".into(),
            rx: 1288490188,
            tx: 356515840,
            last_handshake: Some(1752000000),
        }
    }

    #[test]
    fn card_contains_name_and_traffic() {
        let now = 1_700_000_000;
        let expiry = Some(now + 5 * 86400);
        let text = format_client_card(Lang::Ru, &sample(), now, expiry);
        assert!(text.contains("alice"));
        assert!(text.contains("Активен"));
        assert!(text.contains("1.2 GB"));
        assert!(text.contains("Рукопожатие:")); // строка рукопожатия отрендерена
        assert!(text.contains("ещё")); // истечение через 5 дней
    }

    #[test]
    fn card_escapes_name_html() {
        let now = 1_700_000_000;
        let mut c = sample();
        c.name = "a<b>&c".to_string();
        let text = format_client_card(Lang::Ru, &c, now, None);
        assert!(text.contains("a&lt;b&gt;&amp;c"));
        assert!(!text.contains("a<b>&c"));
    }

    #[test]
    fn card_localized_en() {
        let now = 1_700_000_000;
        let text = format_client_card(Lang::En, &sample(), now, Some(now + 86400));
        assert!(text.contains("Status:"));
        assert!(text.contains("Handshake:"));
        assert!(text.contains("Expires:"));
        assert!(text.contains("1.2 GB"));
        // translated values, not raw backend Russian text
        assert!(text.contains("Active"));
        assert!(text.contains("just now")); // last_handshake is close to `now`
        assert!(text.contains("left")); // expiry is in the future
                                        // no Russian leaked into the EN card
        assert!(!text.contains("Активен"));
        assert!(!text.contains("только что"));
        assert!(!text.contains("ещё"));
    }

    #[test]
    fn stats_counts_clients() {
        let clients = vec![
            sample(),
            Client {
                name: "bob".into(),
                ip: "10.0.0.3".into(),
                client_ipv6: String::new(),
                status: "Неактивен".into(),
                status_code: "inactive".into(),
                rx: 0,
                tx: 0,
                last_handshake: None,
            },
        ];
        let text = format_stats(Lang::Ru, &clients);
        assert!(text.contains("2")); // всего клиентов
        assert!(text.contains("1")); // активных
    }

    #[test]
    fn card_omits_ip_line_when_empty() {
        let now = 1_700_000_000;
        let client = Client {
            name: "charlie".into(),
            ip: String::new(),
            client_ipv6: String::new(),
            status: "Активен".into(),
            status_code: "active".into(),
            rx: 1048576,
            tx: 524288,
            last_handshake: Some(1700000000 - 600),
        };
        let text = format_client_card(Lang::Ru, &client, now, None);
        assert!(!text.contains("IP:"));
        assert!(text.contains("charlie"));
        assert!(text.contains("Трафик"));
    }

    #[test]
    fn send_album_and_filtered_signatures_compile() {
        // Compile-time check: функции существуют с правильными сигнатурами.
        // Реальная отправка тестируется вручную (нужен живой Bot).
        // Оба брала привязаны к одному `'a`, чтобы boxed future жил не дольше.
        fn _assert_send_album<'a>(
            bot: &'a teloxide::Bot,
            chat: teloxide::types::ChatId,
            paths: &'a [String],
        ) -> std::pin::Pin<Box<dyn std::future::Future<Output = crate::error::Result<()>> + 'a>>
        {
            Box::pin(async move { send_album(bot, chat, paths).await })
        }
        fn _assert_filtered<'a>(
            bot: &'a teloxide::Bot,
            chat: teloxide::types::ChatId,
            lang: crate::i18n::Lang,
            res: &'a crate::vpn::model::AddResult,
            conf: bool,
            qr: bool,
            link: bool,
        ) -> std::pin::Pin<Box<dyn std::future::Future<Output = crate::error::Result<()>> + 'a>>
        {
            Box::pin(async move {
                send_client_files_filtered(bot, chat, lang, res, conf, qr, link).await
            })
        }
        // если компилируется — контракт сигнатур соблюдён
    }
}
