name: Deps audit

on:
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check advisories licenses
